[package]
name = "crash_course_BT_YT"
version = "0.1.0"
authors = ["Vaibhav Singh <0vaibhavsingh0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
